%global glib2_version 2.80
%global gtk4_version 4.14
%global vte291_version 0.79
%global json_glib_version 1.6
%global libadwaita_version 1.8
%global libportal_gtk4_version 0.7.1

%global tarball_version %%(echo %{version} | tr '~' '.')

Name:		ptyxis
Version:	50.1
Release:	2%{?dist}.nobara.1
Summary:	A container oriented terminal for GNOME

License:	GPL-2.0-or-later AND GPL-3.0-or-later AND LGPL-3.0-or-later AND LGPL-2.0-or-later AND CC0-1.0
URL:		https://gitlab.gnome.org/chergert/ptyxis
Source0:	https://download.gnome.org/sources/%{name}/50/%{name}-%{tarball_version}.tar.xz
Source1:	org.gnome.Ptyxis.fedora.gschema.override
Source2:        README.nobara

# Native nested terminal panes, focus/navigation, and layout restoration.
Patch0:         0001-native-split-panes.patch
# Run integration tests against the helper built by this RPM.
Patch1:         0002-test-with-built-agent.patch

BuildRequires:	pkgconfig(gio-unix-2.0) >= %{glib2_version}
BuildRequires:	pkgconfig(gtk4) >= %{gtk4_version}
BuildRequires:	pkgconfig(vte-2.91-gtk4) >= %{vte291_version}
BuildRequires:	pkgconfig(libadwaita-1) >= %{libadwaita_version}
BuildRequires:  pkgconfig(libportal-gtk4) >= %{libportal_gtk4_version}
BuildRequires:	pkgconfig(json-glib-1.0) >= %{json_glib_version}
BuildRequires:	desktop-file-utils
BuildRequires:	gcc
BuildRequires:	itstool
BuildRequires:	meson
BuildRequires:	/usr/bin/appstream-util
BuildRequires:  dbus-daemon
BuildRequires:  xorg-x11-server-Xvfb
BuildRequires:  xdotool
BuildRequires:  dejavu-sans-mono-fonts

Requires:	hicolor-icon-theme

# https://fedoraproject.org/wiki/Changes/EncourageI686LeafRemoval
ExcludeArch:	%{ix86}

%description
Ptyxis is a container oriented terminal that provides transparent support for
container systems like Podman, Distrobox, and Toolbx. It also has robust
support for user profiles and native horizontal and vertical split panes.


%prep
%autosetup -p1 -n %{name}-%{tarball_version}
cp -p %{SOURCE2} README.nobara


%build
%meson -Dgeneric=terminal
%meson_build


%install
%meson_install
install -p %{SOURCE1} %{buildroot}%{_datadir}/glib-2.0/schemas
%find_lang %{name} --with-gnome


%check
# An isolated display/bus and in-memory settings exercise real terminal
# processes without touching a desktop session or requiring Ptyxis installed.
xvfb-run -a dbus-run-session -- meson test -C %{_vpath_builddir} --print-errorlogs
appstream-util validate-relax --nonet %{buildroot}%{_metainfodir}/org.gnome.Ptyxis.metainfo.xml
desktop-file-validate %{buildroot}%{_datadir}/applications/org.gnome.Ptyxis.desktop


%files -f %{name}.lang
%doc README.md NEWS README.nobara
%license COPYING
%{_bindir}/ptyxis
%{_libexecdir}/ptyxis-agent
%{_metainfodir}/org.gnome.Ptyxis.metainfo.xml
%{_datadir}/applications/org.gnome.Ptyxis.desktop
%dir %{_datadir}/dbus-1
%dir %{_datadir}/dbus-1/services
%{_datadir}/dbus-1/services/org.gnome.Ptyxis.service
%{_datadir}/glib-2.0/schemas/org.gnome.Ptyxis.gschema.xml
%{_datadir}/glib-2.0/schemas/org.gnome.Ptyxis.fedora.gschema.override
%{_datadir}/icons/hicolor/*/*/*.svg
%{_mandir}/man1/ptyxis.1*

%changelog
* Tue Sep 22 2026 Nobara Project - 50.1-2.nobara.1
- Add nested split panes with resizable dividers and configurable shortcuts
- Preserve pane layouts, focus, profiles, and directories in saved sessions
- Handle close prompts, shell exits, undo, and detached split tabs
- Run split-pane integration tests using the freshly built terminal helper

## START: Generated by rpmautospec
* Sat May 02 2026 Carl George <carlwgeorge@fedoraproject.org> - 50.1-2
- Disable inhibition management by default

* Tue Mar 17 2026 Milan Crha <mcrha@redhat.com> - 50.1-1
- Update to 50.1

* Mon Mar 02 2026 Jan Grulich <jgrulich@redhat.com> - 50~rc-4
- Packit: drop upstream_project_url and rely on release-monitoring only

* Wed Feb 25 2026 Jan Grulich <jgrulich@redhat.com> - 50~rc-3
- Packit: drop fast_forward_merge_into as current stable branches diverge

* Tue Feb 24 2026 Jan Grulich <jgrulich@redhat.com> - 50~rc-1
- Update to 50.rc

* Tue Feb 24 2026 Jan Grulich <jgrulich@redhat.com> - 50~beta-4
- Onboard to Packit for stable Fedora branches

* Thu Jan 29 2026 Packit <hello@packit.dev> - 50~beta-1
- Update to 50.beta upstream release
- Resolves: rhbz#2427228

* Mon Jan 19 2026 Jan Horak <jhorak@redhat.com> - 50~alpha-1
- Update to 50.alpha

* Sat Jan 17 2026 Fedora Release Engineering <releng@fedoraproject.org> - 49.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_44_Mass_Rebuild

* Tue Oct 28 2025 Matthias Clasen <mclasen@redhat.com> - 49.2-1
- Update to 49.2

* Fri Sep 26 2025 Petr Schindler <pschindl@redhat.com> - 49.1-1
- Update to 49.1

* Mon Sep 15 2025 Michael Catanzaro <mcatanzaro@redhat.com> - 49.0-1
- Update to 49.0

* Thu Sep 04 2025 Michael Catanzaro <mcatanzaro@redhat.com> - 49~rc-1
- Update to 49.rc

* Thu Aug 07 2025 nmontero <nmontero@redhat.com> - 49~alpha-1
- Update to 49~alpha

* Thu Aug 07 2025 nmontero <nmontero@redhat.com> - 48.5-1
- Update to 48.5

* Fri Jul 25 2025 Fedora Release Engineering <releng@fedoraproject.org> - 48.4-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild

* Wed May 28 2025 nmontero <nmontero@redhat.com> - 48.4-1
- Update to 48.4

* Thu May 08 2025 nmontero <nmontero@redhat.com> - 48.3-1
- Update to 48.3

* Thu Mar 20 2025 nmontero <nmontero@redhat.com> - 48.1-1
- Update to 48.1

* Mon Mar 17 2025 nmontero <nmontero@redhat.com> - 48.0-1
- Update to 48.0

* Fri Feb 28 2025 nmontero <nmontero@redhat.com> - 48.rc-1
- Update to 48.rc

* Tue Feb 18 2025 nmontero <nmontero@redhat.com> - 47.10-1
- Update to 47.10

* Sat Jan 18 2025 Fedora Release Engineering <releng@fedoraproject.org> - 47.6-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild

* Mon Dec 09 2024 nmontero <nmontero@redhat.com> - 47.6-1
- Update to 47.6

* Mon Nov 25 2024 nmontero <nmontero@redhat.com> - 47.5-1
- Update to 47.5

* Wed Nov 20 2024 nmontero <nmontero@redhat.com> - 47.4-2
- Add Packit configuration for automating release syncing

* Wed Oct 30 2024 nmontero <nmontero@redhat.com> - 47.4-1
- Update to 47.4

* Sat Oct 19 2024 David King <amigadave@amigadave.com> - 47.3-1
- Update to 47.3

* Sat Oct 05 2024 David King <amigadave@amigadave.com> - 47.2-1
- Update to 47.2

* Wed Sep 25 2024 David King <amigadave@amigadave.com> - 47.1-1
- Update to 47.1

* Sun Sep 22 2024 commanderjeanluc <joao.manganelli.86@gmail.com> - 47.0-1
- Update to 47.0

* Tue Sep 17 2024 Yaakov Selkowitz <yselkowi@redhat.com> - 47.rc-2
- Exclude i686

* Thu Sep 12 2024 nmontero <nmontero@redhat.com> - 47.rc-1
- Update to 47.rc

* Mon Aug 12 2024 Michael Catanzaro <mcatanzaro@redhat.com> - 47.beta-2
- Add Fedora gschema override

* Fri Aug 09 2024 nmontero <nmontero@redhat.com> - 47.beta-1
- Update to 47.beta

* Fri Jul 19 2024 Fedora Release Engineering <releng@fedoraproject.org> - 47.alpha-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_41_Mass_Rebuild

* Wed Jul 17 2024 nmontero <nmontero@redhat.com> - 47.alpha-2
- Add patch to fix build failure

* Wed Jul 10 2024 Nieves Montero <nmontero@redhat.com> - 47.alpha-1
- New package. Update 47.alpha
## END: Generated by rpmautospec
