%global forgeurl0 https://github.com/fraunhoferhhi/vvdec
Version: 3.2.0
%global tag0 v%{version}

%forgemeta

Name:           vvdec
Release:        %autorelease
Summary:        The Fraunhofer Versatile Video Decoder

License:        BSD-3-Clause-Clear
URL:            %{forgeurl}
Source0:         %{forgesource}
Source1:           bitstreams.tar.xz
#tar file generated by
#[%]cmake -DVVDEC_ENABLE_BITSTREAM_DOWNLOAD=ON
#tar -cvjf ./bitstreams.tar.xz ./ext/bitstreams
# tests time out on ppc64le
Patch0:        vvdec-increase-test-timeout.patch

BuildRequires: cmake
BuildRequires: ninja-build
#ninja is faster
BuildRequires: gcc
BuildRequires: gcc-c++
BuildRequires: simde-devel

Requires: %{name}-libs%{?_isa} = %{version}-%{release}


%description
VVdeC, the Fraunhofer Versatile Video Encoder, is a fast and efficient
software H.266/VVC encoder implementation


%package devel
Summary: Header files for vvdec development

Requires: %{name}%{?_isa} = %{version}-%{release}

%description devel
The vvdec-devel package contains the header files needed
to develop programs that use the vvdec.


%package libs
Summary: Library  files for vvdec

%description libs
The vvdec-libs package contains the library files

%prep
%forgesetup
%patch -P0 -p1 -b .orig
#sanitize thirdparty
rm -rf ./thirdparty
#prepare test data
tar -xf %{SOURCE1}

%build
%cmake \
                -G Ninja \
                -DCMAKE_BUILD_TYPE=RelWithDebInfo \
                -DVVDEC_ENABLE_LINK_TIME_OPT=ON \
                -DVVDEC_ENABLE_WERROR=OFF \
                -DVVDEC_INSTALL_VVDECAPP=ON \
                -DCMAKE_SKIP_INSTALL_RPATH=1 \
                -DVVDEC_TESTS_DEBUGGER_COMMAND:STRING=""

%cmake_build


%install
%cmake_install


%check
%ctest


%files
%{_bindir}/vvdecapp

%files devel
%{_includedir}/vvdec
%{_libdir}/cmake/vvdec
%{_libdir}/pkgconfig/libvvdec.pc
%{_libdir}/libvvdec.so

%files libs
%{_libdir}/libvvdec.so.3{,.*}
%license LICENSE.txt
%doc README.md
%doc AUTHORS.md

%changelog
%autochangelog
