#!/bin/bash

# Use hhd for Legion Go controller mapping (for now).
# Also we use product_version because for some reason they didn't add the name in product_name
if grep -q "Legion Go" /sys/devices/virtual/dmi/id/product_version; then
        systemctl start hhd@$1.service
fi

# Use hhd for ROG Ally controller mapping (for now).
if grep -q "ROG Ally" /sys/devices/virtual/dmi/id/product_name; then
        systemctl start inputplumber.service
        echo 0 | sudo tee /sys/devices/platform/asus-nb-wmi/mcu_powersave
        if grep -q "ROG Ally X" /sys/devices/virtual/dmi/id/product_name; then
                modprobe -r amd_pmf
                echo "blacklist amd_pmf" | sudo tee /etc/modprobe.d/hhd-blacklist.conf
        fi
fi
