#!/usr/bin/bash

# Become root so we can restart desktop managers
if [[ $EUID != 0 ]]; then
  exec pkexec "$(realpath "$0")" "$@"
fi

# Check if the username argument is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

# Get the username from the first argument
USERNAME=$1

# Find the home directory of the specified user
USER_HOME=$(getent passwd "$USERNAME" | cut -d: -f6)

# Check if the user exists
if [ -z "$USER_HOME" ]; then
  echo "User '$USERNAME' does not exist."
  exit 1
fi

# Define the target directory
TARGET_DIR="$USER_HOME/homebrew/services/"

# Create the target directory if it doesn't exist
if [ ! -d "$TARGET_DIR" ]; then
  mkdir -p "$TARGET_DIR" || { echo "Failed to create directory $TARGET_DIR"; exit 1; }
  chmod -R 775 "$USER_HOME/homebrew/"
  # Copy the PluginLoader
  cp /usr/share/deckyloader/PluginLoader "$TARGET_DIR" || { echo "Failed to copy PluginLoader"; exit 1; }
  cp /usr/share/deckyloader/nobara-preinstalled-plugins.tar.gz "$USER_HOME/homebrew/"
  cd "$USER_HOME/homebrew/"
  tar -xf nobara-preinstalled-plugins.tar.gz
fi

# Start the service
systemctl start "deckyloader@$USERNAME.service" || { echo "Failed to start service"; exit 1; }
