## START: Set by rpmautospec
## (rpmautospec version 0.3.8)
## RPMAUTOSPEC: autochangelog
## END: Set by rpmautospec

Name:           steam-powerbuttond
Version:        0.0.git.4c5087ac
Release:        4%{?dist}
Summary:        Steam Deck power button daemon

License:        BSD
URL:            https://gitlab.steamos.cloud/holo/powerbuttond

BuildRequires:  systemd-rpm-macros
BuildRequires:  libevdev-devel
BuildRequires:  cmake
BuildRequires:  gcc
BuildRequires:  git

Requires:       libevdev

Provides:       steam-powerbuttond
Obsoletes:      gamescope-session-plus <= 0.2.git.201.5538cd66
Provides:       powerbuttond
Obsoletes:      powerbuttond

%description
Steam Deck power button daemon

# Disable debug packages
%define debug_package %{nil}

%prep
%setup -q -n powerbuttond

%install
install -Ds -m 755 steamos-powerbuttond %{buildroot}/usr/lib/hwsupport/steamos-powerbuttond
install -D -m 644 LICENSE %{buildroot}/usr/share/licenses/steamos-powerbuttond/LICENSE
install -D -m 644 steamos-powerbuttond.service %{buildroot}/usr/lib/systemd/user/steamos-powerbuttond.service
install -D -m 644 steamos-power-button.rules %{buildroot}/usr/lib/udev/rules.d/70-steamos-power-button.rules
install -D -m 644 steamos-power-button.hwdb %{buildroot}/usr/lib/udev/hwdb.d/70-steamos-power-button.hwdb
install -d -m 755 %{buildroot}/usr/lib/systemd/user/gamescope-session.service.wants
ln -s ../steamos-powerbuttond.service %{buildroot}/usr/lib/systemd/user/gamescope-session.service.wants/

%post
%systemd_user_post steamos-powerbuttond.service

%preun
%systemd_user_preun steamos-powerbuttond.service

%files
/usr/lib/hwsupport/steamos-powerbuttond
/usr/share/licenses/steamos-powerbuttond/LICENSE
/usr/lib/systemd/user/steamos-powerbuttond.service
/usr/lib/udev/rules.d/70-steamos-power-button.rules
/usr/lib/udev/hwdb.d/70-steamos-power-button.hwdb
/usr/lib/systemd/user/gamescope-session.service.wants/steamos-powerbuttond.service

%changelog
## START: Generated by rpmautospec
* Mon Jan 15 2024 John Doe <packager@example.com> - 0.0.git.1792.086c17c1-1
- Uncommitted changes
## END: Generated by rpmautospec
